### ISSUE TITLE
Playnite fullscreen incompatibility

### ISSUE THREAD

**Issue by giodude12** [LemmusLemmus/GlosSI-Integration-Playnite#12]
If Glosi is enabled for playnite fullscreen mode, then games launch without using glosi. Is this intended behavior?

**Comment by LemmusLemmus** [comment]
No, it is not. When launching games in fullscreen mode it should work exactly the same as in desktop mode. In general, make sure that you have added integration to the games you want to launch with GlosSI (or that you have enabled "Use a default Steam overlay"). Otherwise, something is definitely wrong! To help with troubleshooting, please send the Playnite files `extensions.log` and `playnite.log` (or if the log files are too large, just the last relevant bit is fine). Also, what version of GlosSI are you using?

**Comment by giodude12** [comment]
[extensions.log](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/files/9805125/extensions.log)
[playnite.log](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/files/9805127/playnite.log)

Sorry I took so long, just got home.

Also I'm opening up a new Issue because I found another actual bug I can replicate

**Comment by giodude12** [comment]
any update on this one?

**Comment by LemmusLemmus** [comment]
Sorry, no. I have not yet been able to replicate the issue. I cannot see anything in particular that is wrong in the logs you provided (although I should probably make the logging a bit more informative...).

Can you perhaps describe in more detail what happens? I'm assuming Runbow is one of the games for which the overlay did not open in fullscreen mode? Does the integration work as expected for the same game in desktop mode?

On the off chance that there is some useful information there, could you send the contents of the file `ExtensionsData\6b0297da-75e5-4330-bb2d-b64bff22c315\config.json`?

Normally I would also be interested in the GlosSI logs, but if it works in Playnite desktop mode there is no reason for me to suspected that anything is wrong with the interaction with GlosSI itself.

**Comment by LemmusLemmus** [comment]
If you are using the Playnite overlay option, maybe it is somehow interfering? I guess you could try turning it off and see if that helps.

**Comment by viseniv** [comment]
I have the same problem and if i turn off the playnite overlay option it works fine.

**Comment by LemmusLemmus** [comment]
@viseniv Good to know! Can you describe in more detail what happens? Does it continue to use the Playnite Steam overlay, or is the Playnite overlay simply closed with no new overlay being launched? Do you get a popup from Steam that says it failed to sync by any chance (that would indicate that it attempted to run the game overlay while the Playnite overlay is still running)? Mind sending the log files?

Side note: The next update will change how overlays are launched, so if you are lucky the problem might be fixed by then. But I wouldn't count on it.

**Comment by LemmusLemmus** [comment]
Since a new version that changes when shortcuts are started has been released, has the issue by any chance been fixed now?

**Comment by viseniv** [comment]
No. 
It appears to close the Playnite overlay. 
When i am in the game i don't have the steam overlay menu. 
[extensions.log](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/files/9943755/extensions.log)
[playnite.log](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/files/9943756/playnite.log)

PD: It also this seems a strange, when i launch now playnite and i have the Playnite overlay disabled it seems it is using the desktop configuration but its not. I mapped on the desktop configuration F1 and F2 on the LB and RB buttons but it doesn't work it seems it is using the default desktop configuration (i have mouse on the right trackpad).

**Comment by LemmusLemmus** [comment]
@viseniv Hmm, I can see in the logs that the game overlay does not start properly, but that's about it. Could you enable trace logging in Playnite in order to log more details and send me the new extensions.log file? The option "Log trace messages" should be in "Settings -> For Developers". While you're at it, you could test disabling some or all extensions, to see if any extension is perhaps interfering?

And does the Playnite overlay finish starting before you launch the game? If not, that could be the problem.

Did I understand you correctly that when you are not using the Playnite overlay option, the default desktop configuration that is used is not the one modified by you? If so, that's very weird.

**Comment by viseniv** [comment]
I found the solution of playnite in full screen using my modified desktop by launching steam with admin rights. 
Before i launch the game i wait for the overlay. 
After configuring the desktop configuration i find more convenient than the controller setup (i can use the trackpad as a scroll wheel and i found it very useful)
I will send you the new log

**Comment by LemmusLemmus** [comment]
Here is a GlosSI Integration version that fixes having to wait for the overlay to properly start: [GlosSIIntegration_1_1_0_experimental1.zip](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/files/9946011/GlosSIIntegration_1_1_0_experimental1.zip).
That's about all it does though, and since you said that you did wait for the overlay to start I doubt this will help, but I might as well leave it here anyway as I'm torn on whether to actually release this (simply because I think the solution is ugly).

**Comment by viseniv** [comment]
[playnite.log](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/files/9946798/playnite.log)
[extensions.log](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/files/9946799/extensions.log)
Here are my new logs.
It doesn't work, same thing with the oficial version. I don't know why this happens but now with the custom desktop profile working it's a minor bug.
I found more important a inclusion of a menu in fullscreen to add or delete new profiles to Glossi.
Thanks for your help.

**Comment by LemmusLemmus** [comment]
@viseniv Hmm. Two things that might be worth testing:
1. Does this version of the integration work (if you give the overlay some time to start)? [GlosSIIntegration_1_1_0_experimental2.zip](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/files/9953339/GlosSIIntegration_1_1_0_experimental2.zip). I have added a 5 second delay to the starting of the overlay (most likely an unnecessarily long delay, but it doesn't hurt for testing purposes).
2. If the above does not work, it might be worth testing if the correct Steam shortcut is launched. If you have no Steam overlay currently running and open the Windows run box with "win + R", and run `steam://rungameid/16296785493788459008`, does it start the overlay for, in this case, "Uncharted: Legacy of Thieves Collection"? Or does nothing happen?

Update:
It has been verified that 1. fixes the problem. All that remains is finding a reasonable delay, or fix the underlying problem.

**Comment by LemmusLemmus** [comment]
> I found more important a inclusion of a menu in fullscreen to add or delete new profiles to Glossi.

Good idea! It is unfortunately currently not possible for extensions to add menu entries to Playnite Fullscreen mode, but it is planned for Playnite 11. Once Playnite 11 releases, I'll make sure to add it!

**Comment by LemmusLemmus** [comment]
The overlay switching process has been redesigned, and it now waits for GlosSITarget to launch and open before proceeding with starting the game, so I assume that it has fixed this particular issue? If not, please reply and let me know. (I am closing this issue for now, since I do not know if you still use this unintuitive extension).
