### ISSUE TITLE
I dont have shortcuts.vdf file

### ISSUE THREAD

**Issue by boblehead6** [LemmusLemmus/GlosSI-Integration-Playnite#20]
I looked in the recommened folder path and it wasn't there. I even used the program 'everything' and I couldn't find it anywhere. What can I do?

**Comment by LemmusLemmus** [comment]
Try adding any non-Steam game via Steam and the file should appear (you can then remove the non-Steam game shortcut).
![image](https://user-images.githubusercontent.com/63229554/224655401-1f21db3f-f915-4c02-bbce-1c119e46521e.png)
I'll make sure to update the extension so that the file is created automatically if it is missing...
