### ISSUE TITLE
Can't use the same name in both textboxes.

### ISSUE THREAD

**Issue by Yuzuriha-San** [LemmusLemmus/GlosSI-Integration-Playnite#22]
Triggers Playnite error that tells me to use a different name for one of the the two overlays.

**Comment by LemmusLemmus** [comment]
I am guessing the problem is that you are trying to use the same name via the plus button shortcut creation menu. The plus button next to the text box creates a new, separate, Steam shortcut. And there can only be one with the same name. As long as you have at some point created one shortcut, the name of it can be entered in both text fields, by simply typing the name in the text box without pressing the plus button again.

It is currently not very intuitive at all and should hopefully be simplified in a later version...

If the above is not the solution to the problem, please provide more details.

**Comment by Yuzuriha-San** [comment]
Now it makes sense, all good. Thanks for the reply.
