### ISSUE TITLE
"The shortcuts.vdf file location is incorrect."

### ISSUE THREAD

**Issue by Umbrozium** [LemmusLemmus/GlosSI-Integration-Playnite#30]
My Steam folder is named differently and seemingly because of that, the extension prints this error, not recognizing that this is indeed the Steam directory, and is unable to find shortcuts.vdf. I renamed my folder back to Steam and it did work, but I'd rather this doesn't depend on the folder name.

**Comment by LemmusLemmus** [comment]
Good catch! Another user also encountered this problem and it has been fixed in commit 701757d. Problem is, I have yet to release that version... I ought to do that. In the mean time, you can find the fixed, experimental version of the extension, here: https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/issues/29#issuecomment-1871244689.

Feel free to close the issue if the experimental version solves the issue. Or do not, since it is technically not solved until I actually release the new version... Any day now :)
